### ISSUE TITLE
Make "Server Redirected To" tappable

### ISSUE THREAD

**Issue by tylrtrmbl** [tls-inspector/tls-inspector#112]
**A short description of the feature you're requesting:**

Tapping the "Server Redirected To" cell starts a new query with the specified domain.

**How do you imagine this feature looking? Are there any examples of other implementations?**

Currently, the cell "Server Redirected To" under "SECURITY HTTP HEADERS" gives a text string of the domain an HTTP server is redirecting to. I'm requesting it be made tappable, and that tapping it starts a new query for that domain. It will push a new query onto the stack, pressing "back" goes back to the originally queried domain.

**How do you feel this feature will benefit TLS Inspector?**

It saves the user from needing to manually type the domain name of a redirect.

**Comment by ecnepsnai** [comment]
Hello Taylor, thank you for the suggestion. I like the idea of this, and it shouldn't be too hard to add. I've added it to the queue of features to add in future versions.

**Comment by taylortrimble** [comment]
Cool to see this finished, and already on the App Store! Great job.
