### ISSUE TITLE
Cannot inspect website with IDN (International Domain Name)

### ISSUE THREAD

**Issue by ecnepsnai** [tls-inspector/tls-inspector#43]
Such as the domain https://xn--lv8haa.scotthelme.co.uk/

**Comment by ecnepsnai** [comment]
It appears that CFSockets don't support IDN addresses, even after encoded into punycode.

Might have to use our resolver service to connect to the IP address, although this might not return the correct certificate for shared hosts.

**Comment by Bethannfrum** [comment]
Fix and restore to original form and release old documents
