### ISSUE TITLE
Report if certificate meets App Transport Security requirements. 

### ISSUE THREAD

**Issue by algal** [tls-inspector/tls-inspector#77]
This is a feature suggestions not a bug report. 

I think it would be very convenient if the app could report not only if a certificate is trusted by the system but if it meets Apple’s new standards for “App Transport Security.”

These standards specify allowed ciphers and other requirements, and apps need to request specific exceptions in order to use HTTPS with hosts that don’t meet those standard. 

Why would this be useful? I suspect many of the fans of this app are developers, and it’s a question anyone working on iOS needs to answer about their servers.

**Comment by ecnepsnai** [comment]
Hey Alexis, sorry for taking a bit getting around to this, I don’t seem to get email alerts for new issues 😣.

I’ll spend some time looking into this feature and how I could implement it. Thanks for the suggestion!

**Comment by ecnepsnai** [comment]
Closing as I'm not sure how I'm going to fit this into the app. Most of the ATS requirements are now standard within the system and will reflect in the trust status.
